// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgievohyuujzhnqzqcfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnaWV2b2h5dXVqemhucXpxY2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTA4NzMsImV4cCI6MjA1NzcyNjg3M30.H0nfdDbBIND4oHQu851fcXHdrGEySykOMvLQZaMmvhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);